#!/bin/bash
set -e

function my_print() {
    NEWFILE=~/Downloads/$(basename $1)
    mv $1 $NEWFILE
    vim $NEWFILE
}

if [ -z $1 ]; then
    echo "Usage $0 <filename>"
    exit 1
fi

if [ -f $1 ]; then
    my_print $1
else
    echo "$1 does not exist"
    exit 1
fi
