#!/bin/bash
set -e

result=$(notmuch new)
case "$result"
    "*No new mail*")
        echo $result
        ;;
    "*")
        count=$(notmuch count tag:unread)
        if [ $count -ne 0 ]
            terminal-notifier -message "You have mail!" -subtitle "$count new messages" -contentImage ~/.mutt/mutt-white.png
        fi
        ;;
esac
