#!/bin/bash
set -e

result=`notmuch new`
echo $result
if [ "$result" != "No new mail." ]; then
    count=`notmuch count tag:unread and folder:INBOX`
    echo $count
    if [ $count -ne 0 ]; then
        terminal-notifier -subtitle "You have mail!" -message "$count new messages" -contentImage ~/.mutt/mutt-white.png
    fi
fi
